

GET http://localhost:3000/testApp

###

POST http://localhost:3000/testApp
Content-Type: application/json

{
    "name": "User",
    "password": "password"
}

###

GET http://localhost:3000/testApp/5e8b5c60ca2f241a8c405594

###

DELETE  http://localhost:3000/testApp/5e8b5c60ca2f241a8c405594


###

PATCH http://localhost:3000/testApp/5e8b5c60ca2f241a8c405594
Content-Type: application/json

{
    "name" : "Other Name"
}

###

POST http://localhost:3000/testApp/login/5e8b9ddbe2a4ec1ae01d1a14
Content-Type: application/json

{
    "name": "User",
    "password": "password"
}